version: "3.10"

services:
  redis:
    image: redis
    restart: always
    
  project:
    restart: always
    build: 
      context: ./project
    ports: 
      - "8000:8000"
    command: [ "python3", "bank/manage.py", "runserver", "0.0.0.0:8000"]
  
  worker:
    restart: always
    build: 
      context: ./project

    command: ['celery', '--workdir=bank', '-A', 'config', 'worker' ]