# Generated by Django 4.1 on 2022-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_controller', '0002_alter_cashaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
