# Generated by Django 4.0.7 on 2022-08-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='last_payment_date',
        ),
    ]
