# Generated by Django 4.0.7 on 2022-08-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_controller', '0002_remove_credit_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
    ]
